import Head from "next/head";
import Header from "@/components/header";
import Banner from "@/components/Banner";

import { Nunito } from "@next/font/google";
import SmallCard from "@/components/SmallCard";
import MediumCard from "@/components/MediumCard";
import LargeCard from "@/components/LargeCard";
import Footer from "@/components/Footer";
const nunito = Nunito({ subsets: ["latin"] });

export default function Home({ exploreData, cardsData }) {
    return (
        <>
            <Head>
                <title>Airbnb</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Banner />

            <main className="max-w-[1280px] mx-auto px-8 sm:px-16">
                <section className="pt-6">
                    <h2
                        className={`text-4xl ${nunito.className} font-semibold pb-5`}
                    >
                        Explore nearby
                    </h2>
                    {/* Pulling data from the server using API calls */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                        {exploreData?.map((item) => (
                            <SmallCard
                                key={item.img}
                                img={item.img}
                                distance={item.distance}
                                location={item.location}
                            />
                        ))}
                    </div>
                </section>

                <section className="">
                    <h2 className="text-4xl font-semibold py-8">
                        Live anywhere
                    </h2>

                    <div className="flex space-x-3 overflow-scroll 
                    scrollbar-hide p-3 -ml-3">
                        {cardsData?.map((item) => (
                            <MediumCard key={item.img} {...item} />
                        ))}
                    </div>
                </section>

                <LargeCard 
                    img='https://links.papareact.com/4cj'
                    title='The Greatest Outdoors'
                    description='Wishlists curated by Airbnb'
                    buttonText='Get inspired'
                />
            </main>

            <Footer />

        </>
    );
}

// This function makes the page a server side render
export async function getStaticProps() {
    // 'https://links.papareact.com/pyp'
    const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
        (res) => res.json()
    );

    // https://links.papareact.com/zp1
    const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
        (res) => res.json()
    );

    return {
        props: {
            exploreData,
            cardsData,
        },
    };
}
